### ISSUE TITLE
Request for Dataset

### ISSUE THREAD

**Issue by zhou07** [MungoMeng/Survival-XSurv#1]
I am very interested in your work and want to reproduce your work, but I can not download the dataset of HECKTOR 2022. Could you share the dataset with me?

**Comment by MungoMeng** [comment]
Hi, this data is open source and should be downloaded from the chllenge homepage (https://hecktor.grand-challenge.org/). You should apply for approval from the challenge organizers.

**Comment by zhou07** [comment]
Hi, I already got approval from the organizer but now the data seems gone from the website. As shown in the picture below, I clicked on the download link, but the next page told me there was no data. Could you share the dataset with me?


<img width="798" alt="image" src="https://github.com/MungoMeng/Survival-XSurv/assets/32354174/a15675ed-f52c-45f3-b486-61a179b4b18f">


<img width="871" alt="image" src="https://github.com/MungoMeng/Survival-XSurv/assets/32354174/2e56174d-36ef-47e4-ac0f-b1918df051cf">

**Comment by MungoMeng** [comment]
Hi, if you have already got the approvel but the link is broken. You should report this issue to the organizers and I believe they will fixt this issue very quickly. What I can do is also to share you this broken link.
